PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <https://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX time: <https://www.w3.org/TR/owl-time/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gdprov2: <http://example.org/GDPRov-v2#>


SELECT ?dataCategory ?durationTime ?duration ?durationUnit ?durationComment ?hasDuration
WHERE {
    ?dataCategory rdf:type*/rdfs:subClassOf* gdprov2:PersonalData .
    ?step gdprov2:generatesData ?dataCategory ;
        gdprov2:isPartOfProcess/gdprov2:hasStorageCondition ?storageCondition .

    ?storageCondition gdprov2:hasDuration ?duration .
    ?duration rdf:comment ?durationComment ;
        time:numericDuration ?durationTime ;
        time:unitType ?durationUnit .
}