PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <https://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX time: <https://www.w3.org/TR/owl-time/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gdprov: <http://example.org/GDPRov#>


SELECT ?dataCategory ?durationTime ?duration ?durationUnit ?durationComment ?hasDuration
WHERE {
    ?dataCategory rdf:type/rdfs:subClassOf* gdprov:PersonalData .
    ?step gdprov:collectsData ?dataCategory ;
        gdprov:isPartOfProcess/gdprov:hasStorageCondition ?storageCondition .

    ?storageCondition gdprov:hasDuration ?duration .
    ?duration rdf:comment ?durationComment ;
        time:numericDuration ?durationTime ;
        time:unitType ?durationUnit .
}