PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX time: <https://www.w3.org/TR/owl-time/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX gdprov: <https://w3id.org/GDPRov#>


SELECT ?dataCategory ?storageCondition ?duration ?durationTime ?durationUnit ?durationComment
WHERE {
    ?dataCategory rdf:type/rdfs:subClassOf+ gdprov:Data .
    ?step gdprov:collectsData ?dataCategory ;
        gdprov:isPartOfProcess/gdprov:hasStorageCondition ?storageCondition .

    ?storageCondition gdprov:hasDuration ?duration .

    OPTIONAL { ?duration time:numericDuration ?durationTime . }
    OPTIONAL { ?duration time:unitType ?durationUnit . }
    OPTIONAL { ?duration rdf:comment ?durationComment . }
}