generate_all:
	# drawio2rdf -d base.drawio -l "graffoo v1.2.drawio" -n "CQ08 | Dataset" -o CQ08.ttl
	# drawio2rdf -d base.drawio -l "graffoo v1.2.drawio" -n "CQ28 | Dataset" -o CQ28.ttl
	# drawio2rdf -d base.drawio -l "graffoo v1.2.drawio" -n "CQ29 | Dataset" -o CQ29.ttl
	# drawio2rdf -d base.drawio -l "graffoo v1.2.drawio" -n "CQ51 | Dataset" -o CQ51.ttl
	# drawio2rdf -d base.drawio -l "graffoo v1.2.drawio" -n "CQ63 | Dataset" -o CQ63.ttl
	# drawio2rdf -d base.drawio -l "graffoo v1.2.drawio" -n "CQ64 | Dataset" -o CQ64.ttl
	
	# drawio2rdf -d /home/dprett/projects/master/datasets/SAPOS/base.drawio -l "graffoo v1.2.drawio" -n "CQ29 | Dataset" -o CQ29.ttl